VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.network "private_network", ip: "192.168.42.101"
  #config.vm.network "forwarded_port", guest: 5000, host: 5000
  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "../example-app.git", "/var/git-repositories/example-app.git"
  config.vm.provision "puppet" do |p|
    p.module_path = "modules"
  end
end
