VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.network "private_network", ip: "192.168.42.102"
  #config.vm.network "forwarded_port", guest: 8080, host: 9080
  config.vm.provision "puppet" do |p|
    p.module_path = "modules"
  end
end
